#!/usr/bin/python3

import sys

license_string = """libsoc - Library to handle standardised output files
Copyright (C) 2015 Rikard Nordgren

This file was autogenerated and should not be edited

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

his library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, see <http://www.gnu.org/licenses/>.
"""

default_prefix = "so"

# output_file attribute for the file to output to

def print_license_string(language="C"):
    print_comment(license_string, language)

def print_comment(string, language="C"):
    split = string.splitlines();
   
    language = language.upper()
    sys.stdout = output_file

    # Print the first line
    if language == "C":
        print("/*", split[0])
    elif language == "R" or language == "PYTHON" or language == "PERL":
        print("#", split[0])
    elif language == "FORTRAN":
        print("!", split[0])

    # Print rest of lines
    for line in split[1:]:
        if language == "C":
            print(" *", line)
        elif language == "R" or language == "PYTHON" or language == "PERL":
            print("#", line);
        elif language == "FORTRAN":
            print("!", line)

    if language == "C":
        print(" */")

    sys.stdout = sys.__stdout__

def create_get_name(class_name, attr, prefix=default_prefix):
    return prefix + "_" + class_name + "_get_" + attr

def create_set_name(class_name, attr, prefix=default_prefix):
    return prefix + "_" + class_name + "_set_" + attr
