/* libsoc - Library to handle standardised output files
 * Copyright (C) 2015 Rikard Nordgren
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 * 
 * his library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _PHARMML_PROBONTO_H
#define _PHARMML_PROBONTO_H

#include <stdlib.h>

typedef enum {
    PHARMML_DISTRONAME_UNDEFINED, PHARMML_DISTRONAME_BERNOUILLI1, PHARMML_DISTRONAME_BETABINOMIAL1, PHARMML_DISTRONAME_BINOMIAL1,
    PHARMML_DISTRONAME_CATEGORICALORDERED1, PHARMML_DISTRONAME_CATEGORICALNONORDERED1, PHARMML_DISTRONAME_CONWAYMAXWELLPOISSON1,
    PHARMML_DISTRONAME_DOUBLEPOISSON1, PHARMML_DISTRONAME_GENERALIZEDNEGATIVEBINOMIAL1, PHARMML_DISTRONAME_GENERALIZEDPOISSON1,
    PHARMML_DISTRONAME_GENERALIZEDPOISSON2, PHARMML_DISTRONAME_GENERALIZEDPOISSON3, PHARMML_DISTRONAME_GEOMETRIC1, PHARMML_DISTRONAME_HYPERGEOMETRIC1,
    PHARMML_DISTRONAME_INVERSEBINOMIAL1, PHARMML_DISTRONAME_NEGATIVEBINOMIAL1, PHARMML_DISTRONAME_NEGATIVEBINOMIAL2,
    PHARMML_DISTRONAME_NEGATIVEBINOMIAL3, PHARMML_DISTRONAME_NEGATIVEBINOMIAL4, PHARMML_DISTRONAME_NEGATIVEBINOMIAL5,
    PHARMML_DISTRONAME_POISSON1, PHARMML_DISTRONAME_UNIFORMDISCRETE1, PHARMML_DISTRONAME_UNIFORMDISCRETE2,
    PHARMML_DISTRONAME_ZEROINFLATEDNEGATIVEBINOMIAL1, PHARMML_DISTRONAME_ZEROINFLATEDGENERALIZEDPOISSON1, PHARMML_DISTRONAME_ZEROINFLATEDPOISSON1,
    PHARMML_DISTRONAME_BETA1, PHARMML_DISTRONAME_BIRNBAUMSAUNDERS1, PHARMML_DISTRONAME_CAUCHY1, PHARMML_DISTRONAME_CHISQUARED1,
    PHARMML_DISTRONAME_ERLANG1, PHARMML_DISTRONAME_EXPONENTIAL1, PHARMML_DISTRONAME_EXPONENTIAL2, PHARMML_DISTRONAME_F1, PHARMML_DISTRONAME_F2,
    PHARMML_DISTRONAME_GAMMA1, PHARMML_DISTRONAME_GAMMA2, PHARMML_DISTRONAME_GENERALIZEDGAMMA1, PHARMML_DISTRONAME_GENERALIZEDGAMMA2,
    PHARMML_DISTRONAME_GENERALIZEDGAMMA3, PHARMML_DISTRONAME_GOMPERTZ1, PHARMML_DISTRONAME_GUMBEL1, PHARMML_DISTRONAME_HALFNORMAL1,
    PHARMML_DISTRONAME_INVERSEGAMMA1, PHARMML_DISTRONAME_INVERSEGAUSSIAN1, PHARMML_DISTRONAME_LAPLACE1, PHARMML_DISTRONAME_LAPLACE2,
    PHARMML_DISTRONAME_LOGISTIC1, PHARMML_DISTRONAME_LOGISTIC2, PHARMML_DISTRONAME_LOGLOGISTIC1, PHARMML_DISTRONAME_LOGLOGISTIC2,
    PHARMML_DISTRONAME_LOGNORMAL1, PHARMML_DISTRONAME_LOGNORMAL2, PHARMML_DISTRONAME_LOGNORMAL3, PHARMML_DISTRONAME_LOGNORMAL4,
    PHARMML_DISTRONAME_LOGNORMAL5, PHARMML_DISTRONAME_LOGNORMAL6, PHARMML_DISTRONAME_LOGUNIFORM1, PHARMML_DISTRONAME_NAKAGAMI1,
    PHARMML_DISTRONAME_NORMAL1, PHARMML_DISTRONAME_NORMAL2, PHARMML_DISTRONAME_NORMAL3, PHARMML_DISTRONAME_NORMALINVERSEGAMMA1,
    PHARMML_DISTRONAME_PARETO1, PHARMML_DISTRONAME_RAYLEIGH1, PHARMML_DISTRONAME_STANDARDNORMAL1, PHARMML_DISTRONAME_STANDARDUNIFORM1,
    PHARMML_DISTRONAME_STUDENTT1, PHARMML_DISTRONAME_STUDENTT2, PHARMML_DISTRONAME_TRIANGULAR1, PHARMML_DISTRONAME_TRUNCATEDNORMAL1,
    PHARMML_DISTRONAME_UNIFORM1, PHARMML_DISTRONAME_WEIBULL1, PHARMML_DISTRONAME_WEIBULL2, PHARMML_DISTRONAME_MULTINOMIAL1,
    PHARMML_DISTRONAME_DIRICHLET1, PHARMML_DISTRONAME_INVERSEWISHART1, PHARMML_DISTRONAME_MULTIVARIATENORMAL1,
    PHARMML_DISTRONAME_MULTIVARIATENORMAL2, PHARMML_DISTRONAME_MULTIVARIATESTUDENTT1, PHARMML_DISTRONAME_MULTIVARIATESTUDENTT2,
    PHARMML_DISTRONAME_WISHART1, PHARMML_DISTRONAME_WISHART2, PHARMML_DISTRONAME_MIXTUREDISTRIBUTION, PHARMML_DISTRONAME_RANDOMSAMPLE,
    PHARMML_DISTRONAME_STATISTICALSAMPLE, PHARMML_DISTRONAME_UNKNOWNSAMPLE
} pharmml_DistroNameType;

#endif
