/* libsoc - Library to handle standardised output files
 * Copyright (C) 2015 Rikard Nordgren
 * 
 * This file was autogenerated and should not be edited
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * his library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 */
#ifndef _SO_PRIVATE_SIMULATIONSUBTYPE_H
#define _SO_PRIVATE_SIMULATIONSUBTYPE_H

#include <so/private/Table.h>

struct so_SimulationSubType {
	so_Table *base;
	char *name;
	int *extFileNo;
	int extFileNo_number;
	int reference_count;
};

int so_SimulationSubType_start_element(so_SimulationSubType *self, const char *localname, int nb_attributes, const char **attributes);
void so_SimulationSubType_end_element(so_SimulationSubType *self, const char *localname);
int so_SimulationSubType_characters(so_SimulationSubType *self, const char *ch, int len);
int so_SimulationSubType_xml(so_SimulationSubType *self, xmlTextWriterPtr writer, char *element_name);
int so_SimulationSubType_init_attributes(so_SimulationSubType *self, int nb_attributes, const char **attributes);

#endif
